baseURL = 'https://calheldt.xyz'
languageCode = 'en-us'
title = "Cal's Website"
theme = ["hugo-embed-pdf-shortcode", "toha"]

[build]
  writeStats = true
  buildStatsFile = "hugo_stats.json"

[build.js]
  includePaths = ["node_modules"]

enableInlineShortcodes = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true