baseURL = 'https://calheldt.xyz'
languageCode = 'en-us'
title = "Cal's Website"
theme = 'toha'

[build]
  writeStats = true
  buildStatsFile = "hugo_stats.json"

[build.js]
  includePaths = ["node_modules"]