baseURL = 'https://calheldt.xyz'
languageCode = 'en-us'
title = "Cal's Website"
theme = ["toha"]

[build]
  writeStats = true
  buildStatsFile = "hugo_stats.json"

[build.js]
  includePaths = ["node_modules"]

enableInlineShortcodes = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  [params.features]
    [params.features.theme]
    enable = false
      [params.features.theme.services]
      light = false  # enable light theme. default "true"
      dark = true    # enable dark theme. default "true"
      default = "dark"  # can be either light, dark or system. default "system"