[build.environment]
GO_VERSION = "1.24.5"
HUGO_VERSION = "0.148.2"
NODE_VERSION = "24"
TZ = "America/Los_Angeles"

[build]
publish = "public"
command = "git config core.quotepath false && hugo --gc --minify"